from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from typing import Iterable

# Static CLDR snapshot for countries present in data/airport-codes.csv.
COUNTRY_NAMES_EN = {'AE': 'United Arab Emirates',
 'AF': 'Afghanistan',
 'AG': 'Antigua & Barbuda',
 'AI': 'Anguilla',
 'AL': 'Albania',
 'AM': 'Armenia',
 'AO': 'Angola',
 'AQ': 'Antarctica',
 'AR': 'Argentina',
 'AS': 'American Samoa',
 'AT': 'Austria',
 'AU': 'Australia',
 'AW': 'Aruba',
 'AZ': 'Azerbaijan',
 'BA': 'Bosnia & Herzegovina',
 'BB': 'Barbados',
 'BD': 'Bangladesh',
 'BE': 'Belgium',
 'BF': 'Burkina Faso',
 'BG': 'Bulgaria',
 'BH': 'Bahrain',
 'BI': 'Burundi',
 'BJ': 'Benin',
 'BL': 'St. Barthélemy',
 'BM': 'Bermuda',
 'BN': 'Brunei',
 'BO': 'Bolivia',
 'BQ': 'Caribbean Netherlands',
 'BR': 'Brazil',
 'BS': 'Bahamas',
 'BT': 'Bhutan',
 'BW': 'Botswana',
 'BY': 'Belarus',
 'BZ': 'Belize',
 'CA': 'Canada',
 'CC': 'Cocos (Keeling) Islands',
 'CD': 'Congo - Kinshasa',
 'CF': 'Central African Republic',
 'CG': 'Congo - Brazzaville',
 'CH': 'Switzerland',
 'CI': 'Côte d’Ivoire',
 'CK': 'Cook Islands',
 'CL': 'Chile',
 'CM': 'Cameroon',
 'CN': 'China',
 'CO': 'Colombia',
 'CR': 'Costa Rica',
 'CU': 'Cuba',
 'CV': 'Cape Verde',
 'CW': 'Curaçao',
 'CX': 'Christmas Island',
 'CY': 'Cyprus',
 'CZ': 'Czechia',
 'DE': 'Germany',
 'DJ': 'Djibouti',
 'DK': 'Denmark',
 'DM': 'Dominica',
 'DO': 'Dominican Republic',
 'DZ': 'Algeria',
 'EC': 'Ecuador',
 'EE': 'Estonia',
 'EG': 'Egypt',
 'EH': 'Western Sahara',
 'ER': 'Eritrea',
 'ES': 'Spain',
 'ET': 'Ethiopia',
 'FI': 'Finland',
 'FJ': 'Fiji',
 'FK': 'Falkland Islands',
 'FM': 'Micronesia',
 'FO': 'Faroe Islands',
 'FR': 'France',
 'GA': 'Gabon',
 'GB': 'United Kingdom',
 'GD': 'Grenada',
 'GE': 'Georgia',
 'GF': 'French Guiana',
 'GG': 'Guernsey',
 'GH': 'Ghana',
 'GI': 'Gibraltar',
 'GL': 'Greenland',
 'GM': 'Gambia',
 'GN': 'Guinea',
 'GP': 'Guadeloupe',
 'GQ': 'Equatorial Guinea',
 'GR': 'Greece',
 'GT': 'Guatemala',
 'GU': 'Guam',
 'GW': 'Guinea-Bissau',
 'GY': 'Guyana',
 'HK': 'Hong Kong SAR China',
 'HN': 'Honduras',
 'HR': 'Croatia',
 'HT': 'Haiti',
 'HU': 'Hungary',
 'ID': 'Indonesia',
 'IE': 'Ireland',
 'IL': 'Israel',
 'IM': 'Isle of Man',
 'IN': 'India',
 'IO': 'British Indian Ocean Territory',
 'IQ': 'Iraq',
 'IR': 'Iran',
 'IS': 'Iceland',
 'IT': 'Italy',
 'JE': 'Jersey',
 'JM': 'Jamaica',
 'JO': 'Jordan',
 'JP': 'Japan',
 'KE': 'Kenya',
 'KG': 'Kyrgyzstan',
 'KH': 'Cambodia',
 'KI': 'Kiribati',
 'KM': 'Comoros',
 'KN': 'St. Kitts & Nevis',
 'KP': 'North Korea',
 'KR': 'South Korea',
 'KW': 'Kuwait',
 'KY': 'Cayman Islands',
 'KZ': 'Kazakhstan',
 'LA': 'Laos',
 'LB': 'Lebanon',
 'LC': 'St. Lucia',
 'LK': 'Sri Lanka',
 'LR': 'Liberia',
 'LS': 'Lesotho',
 'LT': 'Lithuania',
 'LU': 'Luxembourg',
 'LV': 'Latvia',
 'LY': 'Libya',
 'MA': 'Morocco',
 'MD': 'Moldova',
 'ME': 'Montenegro',
 'MF': 'St. Martin',
 'MG': 'Madagascar',
 'MH': 'Marshall Islands',
 'MK': 'North Macedonia',
 'ML': 'Mali',
 'MM': 'Myanmar (Burma)',
 'MN': 'Mongolia',
 'MO': 'Macao SAR China',
 'MP': 'Northern Mariana Islands',
 'MQ': 'Martinique',
 'MR': 'Mauritania',
 'MS': 'Montserrat',
 'MT': 'Malta',
 'MU': 'Mauritius',
 'MV': 'Maldives',
 'MW': 'Malawi',
 'MX': 'Mexico',
 'MY': 'Malaysia',
 'MZ': 'Mozambique',
 'NA': 'Namibia',
 'NC': 'New Caledonia',
 'NE': 'Niger',
 'NF': 'Norfolk Island',
 'NG': 'Nigeria',
 'NI': 'Nicaragua',
 'NL': 'Netherlands',
 'NO': 'Norway',
 'NP': 'Nepal',
 'NR': 'Nauru',
 'NU': 'Niue',
 'NZ': 'New Zealand',
 'OM': 'Oman',
 'PA': 'Panama',
 'PE': 'Peru',
 'PF': 'French Polynesia',
 'PG': 'Papua New Guinea',
 'PH': 'Philippines',
 'PK': 'Pakistan',
 'PL': 'Poland',
 'PM': 'St. Pierre & Miquelon',
 'PR': 'Puerto Rico',
 'PT': 'Portugal',
 'PW': 'Palau',
 'PY': 'Paraguay',
 'QA': 'Qatar',
 'RE': 'Réunion',
 'RO': 'Romania',
 'RS': 'Serbia',
 'RU': 'Russia',
 'RW': 'Rwanda',
 'SA': 'Saudi Arabia',
 'SB': 'Solomon Islands',
 'SC': 'Seychelles',
 'SD': 'Sudan',
 'SE': 'Sweden',
 'SG': 'Singapore',
 'SH': 'St. Helena',
 'SI': 'Slovenia',
 'SK': 'Slovakia',
 'SL': 'Sierra Leone',
 'SN': 'Senegal',
 'SO': 'Somalia',
 'SR': 'Suriname',
 'SS': 'South Sudan',
 'ST': 'São Tomé & Príncipe',
 'SV': 'El Salvador',
 'SX': 'Sint Maarten',
 'SY': 'Syria',
 'SZ': 'Eswatini',
 'TC': 'Turks & Caicos Islands',
 'TD': 'Chad',
 'TG': 'Togo',
 'TH': 'Thailand',
 'TJ': 'Tajikistan',
 'TL': 'Timor-Leste',
 'TM': 'Turkmenistan',
 'TN': 'Tunisia',
 'TO': 'Tonga',
 'TR': 'Türkiye',
 'TT': 'Trinidad & Tobago',
 'TV': 'Tuvalu',
 'TW': 'Taiwan',
 'TZ': 'Tanzania',
 'UA': 'Ukraine',
 'UG': 'Uganda',
 'UM': 'U.S. Outlying Islands',
 'US': 'United States',
 'UY': 'Uruguay',
 'UZ': 'Uzbekistan',
 'VC': 'St. Vincent & Grenadines',
 'VE': 'Venezuela',
 'VG': 'British Virgin Islands',
 'VI': 'U.S. Virgin Islands',
 'VN': 'Vietnam',
 'VU': 'Vanuatu',
 'WF': 'Wallis & Futuna',
 'WS': 'Samoa',
 'XK': 'Kosovo',
 'YE': 'Yemen',
 'YT': 'Mayotte',
 'ZA': 'South Africa',
 'ZM': 'Zambia',
 'ZW': 'Zimbabwe'}

COUNTRY_NAMES_ZH = {'AE': '阿联酋',
 'AF': '阿富汗',
 'AG': '安提瓜和巴布达',
 'AI': '安圭拉',
 'AL': '阿尔巴尼亚',
 'AM': '亚美尼亚',
 'AO': '安哥拉',
 'AQ': '南极洲',
 'AR': '阿根廷',
 'AS': '美属萨摩亚',
 'AT': '奥地利',
 'AU': '澳大利亚',
 'AW': '阿鲁巴',
 'AZ': '阿塞拜疆',
 'BA': '波斯尼亚和黑塞哥维那',
 'BB': '巴巴多斯',
 'BD': '孟加拉国',
 'BE': '比利时',
 'BF': '布基纳法索',
 'BG': '保加利亚',
 'BH': '巴林',
 'BI': '布隆迪',
 'BJ': '贝宁',
 'BL': '圣巴泰勒米',
 'BM': '百慕大',
 'BN': '文莱',
 'BO': '玻利维亚',
 'BQ': '荷属加勒比区',
 'BR': '巴西',
 'BS': '巴哈马',
 'BT': '不丹',
 'BW': '博茨瓦纳',
 'BY': '白俄罗斯',
 'BZ': '伯利兹',
 'CA': '加拿大',
 'CC': '科科斯（基林）群岛',
 'CD': '刚果（金）',
 'CF': '中非共和国',
 'CG': '刚果（布）',
 'CH': '瑞士',
 'CI': '科特迪瓦',
 'CK': '库克群岛',
 'CL': '智利',
 'CM': '喀麦隆',
 'CN': '中国',
 'CO': '哥伦比亚',
 'CR': '哥斯达黎加',
 'CU': '古巴',
 'CV': '佛得角',
 'CW': '库拉索',
 'CX': '圣诞岛',
 'CY': '塞浦路斯',
 'CZ': '捷克',
 'DE': '德国',
 'DJ': '吉布提',
 'DK': '丹麦',
 'DM': '多米尼克',
 'DO': '多米尼加共和国',
 'DZ': '阿尔及利亚',
 'EC': '厄瓜多尔',
 'EE': '爱沙尼亚',
 'EG': '埃及',
 'EH': '西撒哈拉',
 'ER': '厄立特里亚',
 'ES': '西班牙',
 'ET': '埃塞俄比亚',
 'FI': '芬兰',
 'FJ': '斐济',
 'FK': '福克兰群岛',
 'FM': '密克罗尼西亚',
 'FO': '法罗群岛',
 'FR': '法国',
 'GA': '加蓬',
 'GB': '英国',
 'GD': '格林纳达',
 'GE': '格鲁吉亚',
 'GF': '法属圭亚那',
 'GG': '根西岛',
 'GH': '加纳',
 'GI': '直布罗陀',
 'GL': '格陵兰',
 'GM': '冈比亚',
 'GN': '几内亚',
 'GP': '瓜德罗普',
 'GQ': '赤道几内亚',
 'GR': '希腊',
 'GT': '危地马拉',
 'GU': '关岛',
 'GW': '几内亚比绍',
 'GY': '圭亚那',
 'HK': '香港',
 'HN': '洪都拉斯',
 'HR': '克罗地亚',
 'HT': '海地',
 'HU': '匈牙利',
 'ID': '印度尼西亚',
 'IE': '爱尔兰',
 'IL': '以色列',
 'IM': '马恩岛',
 'IN': '印度',
 'IO': '英属印度洋领地',
 'IQ': '伊拉克',
 'IR': '伊朗',
 'IS': '冰岛',
 'IT': '意大利',
 'JE': '泽西岛',
 'JM': '牙买加',
 'JO': '约旦',
 'JP': '日本',
 'KE': '肯尼亚',
 'KG': '吉尔吉斯斯坦',
 'KH': '柬埔寨',
 'KI': '基里巴斯',
 'KM': '科摩罗',
 'KN': '圣基茨和尼维斯',
 'KP': '朝鲜',
 'KR': '韩国',
 'KW': '科威特',
 'KY': '开曼群岛',
 'KZ': '哈萨克斯坦',
 'LA': '老挝',
 'LB': '黎巴嫩',
 'LC': '圣卢西亚',
 'LK': '斯里兰卡',
 'LR': '利比里亚',
 'LS': '莱索托',
 'LT': '立陶宛',
 'LU': '卢森堡',
 'LV': '拉脱维亚',
 'LY': '利比亚',
 'MA': '摩洛哥',
 'MD': '摩尔多瓦',
 'ME': '黑山',
 'MF': '法属圣马丁',
 'MG': '马达加斯加',
 'MH': '马绍尔群岛',
 'MK': '北马其顿',
 'ML': '马里',
 'MM': '缅甸',
 'MN': '蒙古',
 'MO': '中国澳门特别行政区',
 'MP': '北马里亚纳群岛',
 'MQ': '马提尼克',
 'MR': '毛里塔尼亚',
 'MS': '蒙特塞拉特',
 'MT': '马耳他',
 'MU': '毛里求斯',
 'MV': '马尔代夫',
 'MW': '马拉维',
 'MX': '墨西哥',
 'MY': '马来西亚',
 'MZ': '莫桑比克',
 'NA': '纳米比亚',
 'NC': '新喀里多尼亚',
 'NE': '尼日尔',
 'NF': '诺福克岛',
 'NG': '尼日利亚',
 'NI': '尼加拉瓜',
 'NL': '荷兰',
 'NO': '挪威',
 'NP': '尼泊尔',
 'NR': '瑙鲁',
 'NU': '纽埃',
 'NZ': '新西兰',
 'OM': '阿曼',
 'PA': '巴拿马',
 'PE': '秘鲁',
 'PF': '法属波利尼西亚',
 'PG': '巴布亚新几内亚',
 'PH': '菲律宾',
 'PK': '巴基斯坦',
 'PL': '波兰',
 'PM': '圣皮埃尔和密克隆群岛',
 'PR': '波多黎各',
 'PT': '葡萄牙',
 'PW': '帕劳',
 'PY': '巴拉圭',
 'QA': '卡塔尔',
 'RE': '留尼汪',
 'RO': '罗马尼亚',
 'RS': '塞尔维亚',
 'RU': '俄罗斯',
 'RW': '卢旺达',
 'SA': '沙特阿拉伯',
 'SB': '所罗门群岛',
 'SC': '塞舌尔',
 'SD': '苏丹',
 'SE': '瑞典',
 'SG': '新加坡',
 'SH': '圣赫勒拿',
 'SI': '斯洛文尼亚',
 'SK': '斯洛伐克',
 'SL': '塞拉利昂',
 'SN': '塞内加尔',
 'SO': '索马里',
 'SR': '苏里南',
 'SS': '南苏丹',
 'ST': '圣多美和普林西比',
 'SV': '萨尔瓦多',
 'SX': '荷属圣马丁',
 'SY': '叙利亚',
 'SZ': '斯威士兰',
 'TC': '特克斯和凯科斯群岛',
 'TD': '乍得',
 'TG': '多哥',
 'TH': '泰国',
 'TJ': '塔吉克斯坦',
 'TL': '东帝汶',
 'TM': '土库曼斯坦',
 'TN': '突尼斯',
 'TO': '汤加',
 'TR': '土耳其',
 'TT': '特立尼达和多巴哥',
 'TV': '图瓦卢',
 'TW': '台湾',
 'TZ': '坦桑尼亚',
 'UA': '乌克兰',
 'UG': '乌干达',
 'UM': '美国本土外小岛屿',
 'US': '美国',
 'UY': '乌拉圭',
 'UZ': '乌兹别克斯坦',
 'VC': '圣文森特和格林纳丁斯',
 'VE': '委内瑞拉',
 'VG': '英属维尔京群岛',
 'VI': '美属维尔京群岛',
 'VN': '越南',
 'VU': '瓦努阿图',
 'WF': '瓦利斯和富图纳',
 'WS': '萨摩亚',
 'XK': '科索沃',
 'YE': '也门',
 'YT': '马约特',
 'ZA': '南非',
 'ZM': '赞比亚',
 'ZW': '津巴布韦'}

COUNTRY_CURRENCIES = {'AE': 'AED',
 'AF': 'AFN',
 'AG': 'XCD',
 'AI': 'XCD',
 'AL': 'ALL',
 'AM': 'AMD',
 'AO': 'AOA',
 'AQ': 'USD',
 'AR': 'ARS',
 'AS': 'USD',
 'AT': 'EUR',
 'AU': 'AUD',
 'AW': 'AWG',
 'AZ': 'AZN',
 'BA': 'BAM',
 'BB': 'BBD',
 'BD': 'BDT',
 'BE': 'EUR',
 'BF': 'XOF',
 'BG': 'BGN',
 'BH': 'BHD',
 'BI': 'BIF',
 'BJ': 'XOF',
 'BL': 'EUR',
 'BM': 'BMD',
 'BN': 'BND',
 'BO': 'BOB',
 'BQ': 'USD',
 'BR': 'BRL',
 'BS': 'BSD',
 'BT': 'INR',
 'BW': 'BWP',
 'BY': 'BYN',
 'BZ': 'BZD',
 'CA': 'CAD',
 'CC': 'AUD',
 'CD': 'CDF',
 'CF': 'XAF',
 'CG': 'XAF',
 'CH': 'CHF',
 'CI': 'XOF',
 'CK': 'NZD',
 'CL': 'CLP',
 'CM': 'XAF',
 'CN': 'CNY',
 'CO': 'COP',
 'CR': 'CRC',
 'CU': 'CUP',
 'CV': 'CVE',
 'CW': 'XCG',
 'CX': 'AUD',
 'CY': 'EUR',
 'CZ': 'CZK',
 'DE': 'EUR',
 'DJ': 'DJF',
 'DK': 'DKK',
 'DM': 'XCD',
 'DO': 'DOP',
 'DZ': 'DZD',
 'EC': 'USD',
 'EE': 'EUR',
 'EG': 'EGP',
 'EH': 'MAD',
 'ER': 'ERN',
 'ES': 'EUR',
 'ET': 'ETB',
 'FI': 'EUR',
 'FJ': 'FJD',
 'FK': 'FKP',
 'FM': 'USD',
 'FO': 'DKK',
 'FR': 'EUR',
 'GA': 'XAF',
 'GB': 'GBP',
 'GD': 'XCD',
 'GE': 'GEL',
 'GF': 'EUR',
 'GG': 'GBP',
 'GH': 'GHS',
 'GI': 'GIP',
 'GL': 'DKK',
 'GM': 'GMD',
 'GN': 'GNF',
 'GP': 'EUR',
 'GQ': 'XAF',
 'GR': 'EUR',
 'GT': 'GTQ',
 'GU': 'USD',
 'GW': 'XOF',
 'GY': 'GYD',
 'HK': 'HKD',
 'HN': 'HNL',
 'HR': 'EUR',
 'HT': 'HTG',
 'HU': 'HUF',
 'ID': 'IDR',
 'IE': 'EUR',
 'IL': 'ILS',
 'IM': 'GBP',
 'IN': 'INR',
 'IO': 'USD',
 'IQ': 'IQD',
 'IR': 'IRR',
 'IS': 'ISK',
 'IT': 'EUR',
 'JE': 'GBP',
 'JM': 'JMD',
 'JO': 'JOD',
 'JP': 'JPY',
 'KE': 'KES',
 'KG': 'KGS',
 'KH': 'KHR',
 'KI': 'AUD',
 'KM': 'KMF',
 'KN': 'XCD',
 'KP': 'KPW',
 'KR': 'KRW',
 'KW': 'KWD',
 'KY': 'KYD',
 'KZ': 'KZT',
 'LA': 'LAK',
 'LB': 'LBP',
 'LC': 'XCD',
 'LK': 'LKR',
 'LR': 'LRD',
 'LS': 'ZAR',
 'LT': 'EUR',
 'LU': 'EUR',
 'LV': 'EUR',
 'LY': 'LYD',
 'MA': 'MAD',
 'MD': 'MDL',
 'ME': 'EUR',
 'MF': 'EUR',
 'MG': 'MGA',
 'MH': 'USD',
 'MK': 'MKD',
 'ML': 'XOF',
 'MM': 'MMK',
 'MN': 'MNT',
 'MO': 'MOP',
 'MP': 'USD',
 'MQ': 'EUR',
 'MR': 'MRU',
 'MS': 'XCD',
 'MT': 'EUR',
 'MU': 'MUR',
 'MV': 'MVR',
 'MW': 'MWK',
 'MX': 'MXN',
 'MY': 'MYR',
 'MZ': 'MZN',
 'NA': 'ZAR',
 'NC': 'XPF',
 'NE': 'XOF',
 'NF': 'AUD',
 'NG': 'NGN',
 'NI': 'NIO',
 'NL': 'EUR',
 'NO': 'NOK',
 'NP': 'NPR',
 'NR': 'AUD',
 'NU': 'NZD',
 'NZ': 'NZD',
 'OM': 'OMR',
 'PA': 'PAB',
 'PE': 'PEN',
 'PF': 'XPF',
 'PG': 'PGK',
 'PH': 'PHP',
 'PK': 'PKR',
 'PL': 'PLN',
 'PM': 'EUR',
 'PR': 'USD',
 'PT': 'EUR',
 'PW': 'USD',
 'PY': 'PYG',
 'QA': 'QAR',
 'RE': 'EUR',
 'RO': 'RON',
 'RS': 'RSD',
 'RU': 'RUB',
 'RW': 'RWF',
 'SA': 'SAR',
 'SB': 'SBD',
 'SC': 'SCR',
 'SD': 'SDG',
 'SE': 'SEK',
 'SG': 'SGD',
 'SH': 'SHP',
 'SI': 'EUR',
 'SK': 'EUR',
 'SL': 'SLE',
 'SN': 'XOF',
 'SO': 'SOS',
 'SR': 'SRD',
 'SS': 'SSP',
 'ST': 'STN',
 'SV': 'USD',
 'SX': 'XCG',
 'SY': 'SYP',
 'SZ': 'SZL',
 'TC': 'USD',
 'TD': 'XAF',
 'TG': 'XOF',
 'TH': 'THB',
 'TJ': 'TJS',
 'TL': 'USD',
 'TM': 'TMT',
 'TN': 'TND',
 'TO': 'TOP',
 'TR': 'TRY',
 'TT': 'TTD',
 'TV': 'AUD',
 'TW': 'TWD',
 'TZ': 'TZS',
 'UA': 'UAH',
 'UG': 'UGX',
 'UM': 'USD',
 'US': 'USD',
 'UY': 'UYU',
 'UZ': 'UZS',
 'VC': 'XCD',
 'VE': 'VES',
 'VG': 'USD',
 'VI': 'USD',
 'VN': 'VND',
 'VU': 'VUV',
 'WF': 'XPF',
 'WS': 'WST',
 'XK': 'EUR',
 'YE': 'YER',
 'YT': 'EUR',
 'ZA': 'ZAR',
 'ZM': 'ZMW',
 'ZW': 'USD'}

MANUAL_COUNTRY_DISPLAY_NAMES = {'AE': '阿联酋',
 'AT': '奥地利',
 'AU': '澳大利亚',
 'BR': '巴西',
 'CA': '加拿大',
 'CH': '瑞士',
 'CN': '中国',
 'DE': '德国',
 'ES': '西班牙',
 'FR': '法国',
 'GB': '英国',
 'GE': '格鲁吉亚',
 'HK': '香港',
 'ID': '印度尼西亚',
 'IE': '爱尔兰',
 'IN': '印度',
 'IT': '意大利',
 'JP': '日本',
 'KR': '韩国',
 'KZ': '哈萨克斯坦',
 'MX': '墨西哥',
 'MY': '马来西亚',
 'NL': '荷兰',
 'PH': '菲律宾',
 'PK': '巴基斯坦',
 'PT': '葡萄牙',
 'QA': '卡塔尔',
 'RU': '俄罗斯',
 'SA': '沙特阿拉伯',
 'SE': '瑞典',
 'SG': '新加坡',
 'TH': '泰国',
 'TR': '土耳其',
 'US': '美国',
 'UZ': '乌兹别克斯坦',
 'VN': '越南'}

MANUAL_COUNTRY_ALIASES = {'ae': 'AE',
 'america': 'US',
 'at': 'AT',
 'au': 'AU',
 'australia': 'AU',
 'austria': 'AT',
 'br': 'BR',
 'brazil': 'BR',
 'britain': 'GB',
 'ca': 'CA',
 'canada': 'CA',
 'ch': 'CH',
 'china': 'CN',
 'cn': 'CN',
 'de': 'DE',
 'england': 'GB',
 'es': 'ES',
 'fr': 'FR',
 'france': 'FR',
 'gb': 'GB',
 'ge': 'GE',
 'georgia': 'GE',
 'germany': 'DE',
 'great britain': 'GB',
 'hk': 'HK',
 'hong kong': 'HK',
 'id': 'ID',
 'ie': 'IE',
 'in': 'IN',
 'india': 'IN',
 'indonesia': 'ID',
 'ireland': 'IE',
 'it': 'IT',
 'italy': 'IT',
 'japan': 'JP',
 'jp': 'JP',
 'kazakhstan': 'KZ',
 'korea': 'KR',
 'kr': 'KR',
 'kz': 'KZ',
 'malaysia': 'MY',
 'mexico': 'MX',
 'mx': 'MX',
 'my': 'MY',
 'netherlands': 'NL',
 'nl': 'NL',
 'pakistan': 'PK',
 'ph': 'PH',
 'philippines': 'PH',
 'pk': 'PK',
 'portugal': 'PT',
 'pt': 'PT',
 'qa': 'QA',
 'qatar': 'QA',
 'ru': 'RU',
 'russia': 'RU',
 'sa': 'SA',
 'saudi arabia': 'SA',
 'se': 'SE',
 'sg': 'SG',
 'singapore': 'SG',
 'south korea': 'KR',
 'spain': 'ES',
 'sweden': 'SE',
 'switzerland': 'CH',
 'th': 'TH',
 'thailand': 'TH',
 'tr': 'TR',
 'turkey': 'TR',
 'turkiye': 'TR',
 'uae': 'AE',
 'uk': 'GB',
 'united arab emirates': 'AE',
 'united kingdom': 'GB',
 'united states': 'US',
 'us': 'US',
 'usa': 'US',
 'uz': 'UZ',
 'uzbekistan': 'UZ',
 'vietnam': 'VN',
 'vn': 'VN',
 '中国': 'CN',
 '乌兹别克斯坦': 'UZ',
 '俄罗斯': 'RU',
 '加拿大': 'CA',
 '卡塔尔': 'QA',
 '印尼': 'ID',
 '印度': 'IN',
 '印度尼西亚': 'ID',
 '哈萨克斯坦': 'KZ',
 '土耳其': 'TR',
 '墨西哥': 'MX',
 '奥地利': 'AT',
 '巴基斯坦': 'PK',
 '巴西': 'BR',
 '德国': 'DE',
 '意大利': 'IT',
 '新加坡': 'SG',
 '日本': 'JP',
 '格鲁吉亚': 'GE',
 '沙特阿拉伯': 'SA',
 '法国': 'FR',
 '泰国': 'TH',
 '澳大利亚': 'AU',
 '爱尔兰': 'IE',
 '瑞典': 'SE',
 '瑞士': 'CH',
 '美国': 'US',
 '英国': 'GB',
 '荷兰': 'NL',
 '菲律宾': 'PH',
 '葡萄牙': 'PT',
 '西班牙': 'ES',
 '越南': 'VN',
 '阿联酋': 'AE',
 '韩国': 'KR',
 '香港': 'HK',
 '马来西亚': 'MY'}


@dataclass(frozen=True)
class CountryInfo:
    code: str
    zh_name: str
    en_name: str
    currency: str
    aliases: tuple[str, ...]


def normalize_country_code(value: str) -> str:
    return value.strip().upper()


def iter_cldr_country_codes() -> tuple[str, ...]:
    return tuple(COUNTRY_NAMES_EN)


@lru_cache(maxsize=None)
def get_country_info(country_code: str) -> CountryInfo:
    code = normalize_country_code(country_code)
    zh_name = MANUAL_COUNTRY_DISPLAY_NAMES.get(code) or COUNTRY_NAMES_ZH.get(code) or COUNTRY_NAMES_EN.get(code) or code
    en_name = COUNTRY_NAMES_EN.get(code) or COUNTRY_NAMES_ZH.get(code) or MANUAL_COUNTRY_DISPLAY_NAMES.get(code) or code
    return CountryInfo(code, zh_name, en_name, get_country_currency(code), _build_aliases(code, zh_name, en_name))


def get_country_display_name(country_code: str) -> str:
    return get_country_info(country_code).zh_name


def get_country_currency(country_code: str) -> str:
    return COUNTRY_CURRENCIES.get(normalize_country_code(country_code), "USD")


def build_country_alias_map(country_codes: Iterable[str]) -> dict[str, str]:
    codes = {normalize_country_code(item) for item in country_codes}
    aliases: dict[str, str] = {}
    for code in codes:
        for alias in get_country_info(code).aliases:
            aliases.setdefault(alias.strip().lower(), code)
    for alias, raw_code in MANUAL_COUNTRY_ALIASES.items():
        code = normalize_country_code(raw_code)
        if code in codes:
            aliases[alias.strip().lower()] = code
    return aliases


def _build_aliases(code: str, zh_name: str, en_name: str) -> tuple[str, ...]:
    aliases = {code, code.lower(), zh_name, zh_name.lower(), en_name, en_name.lower()}
    aliases.update(alias for alias, target in MANUAL_COUNTRY_ALIASES.items() if normalize_country_code(target) == code)
    return tuple(sorted(filter(None, aliases)))
